### PR TITLE
Update Maskrcnn Trainer & Add FasterRCNN configs

### PR DESCRIPTION
**Pull request by Zha0q1**
Updating Mask/FasterRCNN `trainer.py` to be in sync with master branch (so that their logging behavior is the same).

### CODE REVIEW

**Comment by Zha0q1** [comment]
@rondogency @karan6181 Do you see this change breaking any nightly benchmarks (maybe the metrics parser there rely on the current logging behavior?)?

**Comment by rondogency** [comment]
did you test it on your end? if it passes we should be good

**Comment by Zha0q1** [comment]
Yes, this is tested -- I applied these changes on top of `570106654206.dkr.ecr.us-west-2.amazonaws.com/smddp:cu111-pt-1.8.1-maskrcnn-nccl` and used the images to train FasterRCNN. Logging behavior was the same as that in master branch now

**Comment by Zha0q1** [comment]
My concern is that if there is any metrics parsing script relying on the existing logging behavior in the nccl branch, then this will break things. Otherwise this pr along should be fine.

**Review by yselivonchyk — APPROVED** [review]

**Review by rondogency — APPROVED** [review]

**Pull request merged**
